import time
import re

def clean_html(text):
    """Remove all HTML tags and decode entities."""
    if not text:
        return ""
    
    # 移除所有 HTML 标签 (包括 <a>, <p>, <br>, <strong> 等)
    text = re.sub(r'<[^>]+>', '', text)
    
    # 解码常见 HTML 实体
    html_entities = {
        '&nbsp;': ' ',
        '&amp;': '&',
        '&lt;': '<',
        '&gt;': '>',
        '&quot;': '"',
        '&#39;': "'",
        '&hellip;': '...',
        '&mdash;': '—',
        '&ndash;': '-',
    }
    for entity, char in html_entities.items():
        text = text.replace(entity, char)
    
    # 移除多余空白
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

def truncate_text(text, max_length=100):
    """Safely truncate text without breaking words."""
    if not text or len(text) <= max_length:
        return text
    
    # 在 max_length 附近找到最近的空格或标点
    truncated = text[:max_length]
    last_space = truncated.rfind(' ')
    if last_space > max_length * 0.7:  # 如果空格位置合理
        truncated = truncated[:last_space]
    
    return truncated.rstrip('.,;:!?') + "..."

def format_time(published):
    """Format published time to readable string."""
    if not published:
        return ""
    try:
        # published 是 time.struct_time 格式
        if hasattr(published, 'tm_year'):
            return time.strftime('%m-%d %H:%M', published)
        return ""
    except:
        return ""

def format_items(source_name, items):
    """Format items into DingTalk Markdown."""
    if not items:
        return None
    
    # 添加关键词以通过钉钉过滤
    text = f"## 🤖 AI简讯 \n\n---\n\n"
    for item in items:
        # 清理标题和摘要中的 HTML
        title = clean_html(item['title'])
        summary = clean_html(item['summary'])
        
        # 格式化发布时间
        pub_time = format_time(item.get('published'))
        
        # 安全截断摘要
        summary = truncate_text(summary, 120)
        
        # 标题
        text += f"**[{title}]({item['link']})**\n\n"
        # 时间标签单独一行
        if pub_time:
            text += f" {pub_time}\n\n"
        if summary:
            text += f"> {summary}\n\n"
        else:
            text += "\n"
        
    text += f"\n_Generated by aiBox at {time.strftime('%H:%M')}_"
    return text
